/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os tenants (MASTER) */
        get: operations["TenantController_findAll"];
        put?: never;
        /** Criar tenant (MASTER) */
        post: operations["TenantController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter próprio tenant (ADMIN) */
        get: operations["TenantController_findOwn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar nome e branding do próprio tenant (ADMIN) */
        patch: operations["TenantController_updateOwn"];
        trace?: never;
    };
    "/api/v1/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar tenant por ID (MASTER) */
        get: operations["TenantController_findById"];
        put?: never;
        post?: never;
        /** Desativar tenant (MASTER) */
        delete: operations["TenantController_deactivate"];
        options?: never;
        head?: never;
        /** Atualizar tenant (MASTER) */
        patch: operations["TenantController_update"];
        trace?: never;
    };
    "/api/v1/boloes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar bolões do tenant */
        get: operations["BolaoController_findAll"];
        put?: never;
        /** Criar bolão com categorias (soma=100%) */
        post: operations["BolaoController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar bolão por ID (com categorias) */
        get: operations["BolaoController_findById"];
        put?: never;
        post?: never;
        /** Excluir bolão (somente quando A_SER_INICIADO) */
        delete: operations["BolaoController_delete"];
        options?: never;
        head?: never;
        /** Atualizar bolão (somente quando A_SER_INICIADO) */
        patch: operations["BolaoController_update"];
        trace?: never;
    };
    "/api/v1/boloes/{id}/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Substituir todas as categorias do bolão (soma=100%) */
        patch: operations["BolaoController_updateCategorias"];
        trace?: never;
    };
    "/api/v1/boloes/{id}/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Iniciar bolão (A_SER_INICIADO → EM_ANDAMENTO) */
        patch: operations["BolaoController_iniciar"];
        trace?: never;
    };
    "/api/v1/boloes/{id}/finalizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Finalizar bolão (EM_ANDAMENTO → FINALIZADO) */
        patch: operations["BolaoController_finalizar"];
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/cotas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar cotas do bolão (filtro por status e busca) */
        get: operations["ParticipanteController_findAll"];
        put?: never;
        /** Criar cota com palpites (10 números únicos, 1–60) */
        post: operations["ParticipanteController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/cotas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar cota por ID */
        get: operations["ParticipanteController_findById"];
        put?: never;
        post?: never;
        /** Excluir cota (só PENDENTE) */
        delete: operations["ParticipanteController_delete"];
        options?: never;
        head?: never;
        /** Atualizar cota (só PENDENTE) */
        patch: operations["ParticipanteController_update"];
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/cotas/{id}/pagar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirmar pagamento (PENDENTE → PAGO) */
        patch: operations["ParticipanteController_confirmarPagamento"];
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/cotas/{id}/inativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Inativar cota (PENDENTE ou PAGO → INATIVO) */
        patch: operations["ParticipanteController_inativar"];
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/sorteios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar sorteios do bolão (ordem sequencial) */
        get: operations["SorteioController_findAll"];
        put?: never;
        /** Registrar sorteio e disparar cálculo de acertos (BullMQ) */
        post: operations["SorteioController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/sorteios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar sorteio por ID */
        get: operations["SorteioController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/sorteios/{id}/reprocessar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocessar acertos de um sorteio (MASTER) */
        post: operations["SorteioController_reprocessar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/premios/calcular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calcular e distribuir prêmios (idempotente — bolão deve ser FINALIZADO) */
        post: operations["PremioController_calcular"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/premios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar prêmios do bolão */
        get: operations["PremioController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/premios/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranking de participantes por total de acertos (cotas PAGO) */
        get: operations["PremioController_getRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/premios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar prêmio por ID */
        get: operations["PremioController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/premios/{id}/pagar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marcar prêmio como pago (PENDENTE → PAGO) */
        patch: operations["PremioController_pagar"];
        trace?: never;
    };
    "/api/v1/whatsapp/sessao/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar/retomar sessão WhatsApp do tenant (retorna status ou QR code) */
        post: operations["WhatsAppSessionController_iniciar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/sessao/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status da sessão WhatsApp (polling para acompanhar QR → CONECTADO) */
        get: operations["WhatsAppSessionController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/sessao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Encerrar sessão WhatsApp do tenant */
        delete: operations["WhatsAppSessionController_encerrar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/sessao/grupos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar grupos WhatsApp (requer status CONECTADO) */
        get: operations["WhatsAppSessionController_getGrupos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/mensagens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de mensagens WhatsApp */
        get: operations["WhatsAppMensagemController_findAll"];
        put?: never;
        /** Enfileirar mensagem WhatsApp (enviada via BullMQ) */
        post: operations["WhatsAppMensagemController_enfileirar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/mensagens/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reenviar mensagem FALHA */
        post: operations["WhatsAppMensagemController_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/google-drive/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Importar cotas de Google Sheets (Service Account) */
        post: operations["GoogleDriveController_importarCotas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/google-drive/exportar/resultados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exportar ranking para Google Sheets (sobrescreve aba) */
        post: operations["GoogleDriveController_exportarResultados"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/relatorios/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gerar XLSX de ranking + prêmios (upload no Supabase Storage → URL assinada 24h) */
        post: operations["RelatorioController_gerarXlsx"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boloes/{bolaoId}/relatorios/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gerar PDF completo (prêmios + ranking até 200 cotas → URL assinada 24h) */
        post: operations["RelatorioController_gerarPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pwa/manifest.webmanifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Web App Manifest dinâmico por tenant (X-Tenant-Id header) */
        get: operations["PwaController_getManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pwa/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Branding do tenant para bootstrap do frontend */
        get: operations["PwaController_getTenantConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TenantBrandingDto: {
            /** @example https://cdn.exemplo.com/logo.png */
            logoUrl?: string;
            /** @example #1F4E79 */
            corPrimaria?: string;
            /** @example Meu Bolão */
            nomeCustomizado?: string;
        };
        CreateTenantDto: {
            /** @example Bolão do João */
            nome: string;
            /** @example bolao-do-joao */
            slug: string;
            /** @example 15 */
            taxaAdministrativaPct?: number;
            branding?: components["schemas"]["TenantBrandingDto"];
        };
        UpdateOwnTenantDto: {
            /** @example Meu Bolão Atualizado */
            nome?: string;
            branding?: components["schemas"]["TenantBrandingDto"];
        };
        UpdateTenantDto: {
            /** @example Bolão do João */
            nome?: string;
            /** @example bolao-do-joao */
            slug?: string;
            /** @example 15 */
            taxaAdministrativaPct?: number;
            branding?: components["schemas"]["TenantBrandingDto"];
        };
        CreateCategoriaDto: {
            /** @example Premio Principal */
            nome: string;
            /** @enum {string} */
            tipo: "TAXA_ADMINISTRATIVA" | "ACERTOS_EXATOS" | "MAIOR_PONTUACAO_SORTEIO" | "MAIOR_PONTUACAO_GERAL" | "MENOR_PONTUACAO_GERAL";
            /**
             * @description Obrigatório quando tipo=ACERTOS_EXATOS
             * @example 10
             */
            acertosAlvo?: number;
            /**
             * @description Obrigatório quando tipo=MAIOR_PONTUACAO_SORTEIO
             * @example 1
             */
            sorteioReferencia?: number;
            /** @example 55 */
            percentual: number;
            /** @example false */
            acumulaSemGanhador?: boolean;
            /** @example 1 */
            ordem?: number;
        };
        CreateBolaoDto: {
            /** @example Bolão Mega-Sena Abril 2026 */
            nome: string;
            /** @example 30 */
            valorCota: number;
            /** @example 2026-04-01 */
            dataInicio?: string;
            /** @example 2026-04-23 */
            dataTermino?: string;
            categorias: components["schemas"]["CreateCategoriaDto"][];
        };
        UpdateBolaoDto: {
            /** @example Bolão Maio 2026 */
            nome?: string;
            /** @example 35 */
            valorCota?: number;
            /** @example 2026-05-01 */
            dataInicio?: string;
            /** @example 2026-05-31 */
            dataTermino?: string;
        };
        UpdateCategoriasDto: {
            categorias: components["schemas"]["CreateCategoriaDto"][];
        };
        CreateCotaDto: {
            /** @example JOÃO DA SILVA */
            nomeIdentificacao: string;
            /** @example 83999990000 */
            numeroCelular?: string;
            /**
             * @description 10 números únicos entre 1 e 60
             * @example [
             *       1,
             *       7,
             *       8,
             *       14,
             *       15,
             *       23,
             *       26,
             *       32,
             *       42,
             *       55
             *     ]
             */
            palpites: string[];
        };
        UpdateCotaDto: {
            /** @example MARIA DA SILVA */
            nomeIdentificacao?: string;
            /** @example 83988880000 */
            numeroCelular?: string;
            /**
             * @example [
             *       2,
             *       8,
             *       9,
             *       15,
             *       16,
             *       24,
             *       27,
             *       33,
             *       43,
             *       56
             *     ]
             */
            palpites?: string[];
        };
        CreateSorteioDto: {
            /**
             * @description Número do concurso da Mega-Sena
             * @example 2994
             */
            numeroConcurso: number;
            /** @example 2026-04-09 */
            dataSorteio: string;
            /**
             * @description 6 números únicos entre 1 e 60
             * @example [
             *       1,
             *       10,
             *       23,
             *       31,
             *       40,
             *       55
             *     ]
             */
            bolasSorteadas: string[];
        };
        EnviarMensagemDto: {
            /**
             * @description ID do grupo WhatsApp (obtido em /whatsapp/sessao/grupos)
             * @example 120363000000000000@g.us
             */
            grupoId: string;
            /** @enum {string} */
            tipo: "RESULTADO_SORTEIO" | "RANKING_PARCIAL" | "PREMIADOS" | "AVISO_ADMIN" | "MANUAL";
            /**
             * @example 🏆 *Resultado do Sorteio #2994*
             *     ...
             */
            conteudo: string;
            /** @description Bolão ao qual a mensagem se refere */
            bolaoId?: string;
        };
        ImportCotasDto: {
            /** @example 1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms */
            spreadsheetId: string;
            /**
             * @description Range do Google Sheets. Formato esperado: Col A=Nome, B=Celular, C-L=10 Palpites
             * @example Plan1!A2:L1000
             */
            range?: string;
            /**
             * @description Se true, pula linhas inválidas; se false, aborta na primeira
             * @default true
             */
            ignorarErros: boolean;
        };
        ExportarResultadosDto: {
            /** @example 1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms */
            spreadsheetId: string;
            /**
             * @description Nome da aba a ser sobrescrita
             * @example Ranking
             */
            aba?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TenantController_findAll: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantController_findOwn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantController_updateOwn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOwnTenantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BolaoController_findAll: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BolaoController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBolaoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BolaoController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BolaoController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BolaoController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBolaoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BolaoController_updateCategorias: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoriasDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BolaoController_iniciar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BolaoController_finalizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParticipanteController_findAll: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                status?: "PENDENTE" | "PAGO" | "INATIVO";
                /** @description Busca por nome ou celular */
                busca?: string;
            };
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParticipanteController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCotaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParticipanteController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParticipanteController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParticipanteController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCotaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParticipanteController_confirmarPagamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParticipanteController_inativar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SorteioController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SorteioController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSorteioDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SorteioController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SorteioController_reprocessar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PremioController_calcular: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PremioController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PremioController_getRanking: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PremioController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PremioController_pagar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatsAppSessionController_iniciar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatsAppSessionController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatsAppSessionController_encerrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatsAppSessionController_getGrupos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatsAppMensagemController_findAll: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                status?: "PENDENTE" | "ENVIADO" | "FALHA";
                tipo?: "RESULTADO_SORTEIO" | "RANKING_PARCIAL" | "PREMIADOS" | "AVISO_ADMIN" | "MANUAL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatsAppMensagemController_enfileirar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnviarMensagemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatsAppMensagemController_retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoogleDriveController_importarCotas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportCotasDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoogleDriveController_exportarResultados: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportarResultadosDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RelatorioController_gerarXlsx: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RelatorioController_gerarPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bolaoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PwaController_getManifest: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PwaController_getTenantConfig: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
